# Tensor 基础操作
tensor 与 ndarray 的很多逻辑是相同的，主要增加了一些深度学习需要的功能：
- 自动微分，计算梯度
- 支持 GPU 运算

In [1]:
import torch

# 手动创建
tensor_manual = torch.tensor([[1, 2], [3, 4]])
print("手动创建tensor:\n", tensor_manual)

# 全零、全一和随机tensor
tensor_zeros = torch.zeros((2, 3))
tensor_ones = torch.ones((2, 3))
tensor_rand = torch.rand((2, 3))
print("全零tensor:\n", tensor_zeros)
print("全一tensor:\n", tensor_ones)
print("随机tensor:\n", tensor_rand)

手动创建tensor:
 tensor([[1, 2],
        [3, 4]])
全零tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
全一tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
随机tensor:
 tensor([[0.4428, 0.6196, 0.3246],
        [0.6618, 0.4253, 0.1930]])


In [2]:
tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0]], dtype=torch.float32)

print("形状:", tensor.shape)
print("数据类型:", tensor.dtype)
print("设备:", tensor.device)

形状: torch.Size([2, 2])
数据类型: torch.float32
设备: cpu


In [3]:
# 基本加法运算
tensor1 = torch.tensor([1.0, 2.0, 3.0])
tensor2 = torch.tensor([4.0, 5.0, 6.0])
print("加法:", tensor1 + tensor2)

# 广播机制
tensor3 = torch.tensor([[1, 2], [3, 4]])
tensor_broadcast = tensor3 + torch.tensor([1, 2])
print("广播加法:\n", tensor_broadcast)

# 将tensor移动到GPU
if torch.cuda.is_available():
    tensor_gpu = tensor1.to("cuda")
    print("在GPU上的tensor:", tensor_gpu)


加法: tensor([5., 7., 9.])
广播加法:
 tensor([[2, 4],
        [4, 6]])


In [4]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# 重塑
reshaped_tensor = tensor.reshape(3, 2)
print("重塑后的tensor:\n", reshaped_tensor)

# 转置
transposed_tensor = tensor.transpose(0, 1)
print("转置后的tensor:\n", transposed_tensor)

重塑后的tensor:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])
转置后的tensor:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [10]:
# 创建需要梯度的tensor
x = torch.tensor([2.0, 3.0], requires_grad=True)
y = x * x  # 操作
y_sum = y.sum()  # 求和，只能对标量调用backward()
y_sum.backward()  # 计算梯度
print("x:", x)
print("y:", y)
print("y_sum:", y_sum)
print("x的梯度:", x.grad)  # 输出 tensor([4., 6.])

x: tensor([2., 3.], requires_grad=True)
y: tensor([4., 9.], grad_fn=<MulBackward0>)
y_sum: tensor(13., grad_fn=<SumBackward0>)
x的梯度: tensor([4., 6.])


In [8]:
import numpy as np
# 从ndarray转换为tensor
numpy_array = np.array([1, 2, 3])
tensor_from_numpy = torch.from_numpy(numpy_array)
print("从ndarray转换为tensor:", tensor_from_numpy)

# 从tensor转换为ndarray
tensor = torch.tensor([4.0, 5.0, 6.0])
numpy_from_tensor = tensor.numpy()
print("从tensor转换为ndarray:", numpy_from_tensor)

从ndarray转换为tensor: tensor([1, 2, 3], dtype=torch.int32)
从tensor转换为ndarray: [4. 5. 6.]
