In [24]:
from torch import nn
import torch


def vgg_block(in_channels, out_channels, num_layers):
    layers = []
    for _ in range(num_layers):
        layers.append(nn.Conv2d(in_channels, out_channels, 3, padding=1))
        layers.append(nn.ReLU())
        in_channels = out_channels
    layers.append(nn.MaxPool2d(kernel_size=2, stride=2))
    return nn.Sequential(*layers)

def vgg(conv_arch, num_classes=10):
    conv_blocks = []
    in_channels=3
    for (num_layers, out_channels) in conv_arch:
        conv_blocks.append(vgg_block(in_channels, out_channels, num_layers))
        in_channels = out_channels
        
    return nn.Sequential(
        *conv_blocks,
        nn.Flatten(),
        nn.Linear(out_channels * 7 * 7, 4096),
        nn.ReLU(),
        nn.Dropout(0.5),
        nn.Linear(4096, 4096),
        nn.ReLU(),
        nn.Dropout(0.5),
        nn.Linear(4096, num_classes)
    )

In [25]:
class VGG(nn.Module):
    def __init__(self, conv_arch, num_classes=10):
        super(VGG, self).__init__()
        self.features = vgg(conv_arch, num_classes=num_classes)
        
    def forward(self, x):
        x = self.features(x)
        return x

In [26]:
# 生成随机输入
x = torch.rand(1, 3, 224, 224)


In [27]:
vgg11 = VGG(((1,64), (1,128), (2,256), (2,512), (2,512)))
out = vgg11(x)
print(out)
# print(vgg11)

tensor([[-0.0114,  0.0168,  0.0045, -0.0012,  0.0037, -0.0074,  0.0171,  0.0163,
          0.0063, -0.0032]], grad_fn=<AddmmBackward0>)


In [28]:
vgg13 = VGG(((2,64), (2,128), (2,256), (2,512), (2,512)))
out = vgg13(x)
print(out)

tensor([[-0.0025, -0.0088,  0.0046, -0.0046,  0.0094, -0.0047, -0.0089,  0.0032,
         -0.0031,  0.0128]], grad_fn=<AddmmBackward0>)


In [29]:
vgg16 = VGG(((2,64), (2,128), (3,256), (3,512), (3,512)))
out = vgg16(x)
print(out)

tensor([[ 0.0150,  0.0046,  0.0076,  0.0070, -0.0161,  0.0169, -0.0048, -0.0064,
          0.0048, -0.0227]], grad_fn=<AddmmBackward0>)


In [30]:
vgg19 = VGG(((2,64), (2,128), (4,256), (4,512), (4,512)), num_classes=5)
out = vgg19(x)
print(out)

tensor([[ 0.0177,  0.0060, -0.0123,  0.0071, -0.0060]],
       grad_fn=<AddmmBackward0>)


In [31]:
vgg19

VGG(
  (features): Sequential(
    (0): Sequential(
      (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU()
      (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU()
      (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    )
    (1): Sequential(
      (0): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU()
      (2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU()
      (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    )
    (2): Sequential(
      (0): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU()
      (2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU()
      (4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (5): ReLU()
      (6): Conv2d(256, 256, kernel_size=(3, 3), s